version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    IMAGE_REPO_NAME: brain-tasks-app
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region  | docker login --username AWS --password-stdin 941178225946.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t : ./Brain-Tasks-App
      - docker tag : 941178225946.dkr.ecr.ap-south-1.amazonaws.com/:

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push 941178225946.dkr.ecr.ap-south-1.amazonaws.com/:
      - echo Build completed
